stages:
  - test
  - deploy

variables:
  RUBYSUFFIX: '23'
  MODULENAME: 'vmd'

puppet-lint:
  script:
    - "puppet-lint${RUBYSUFFIX} --relative --fail-on-warnings --with-filename --with-context manifests"
  stage: test

template-test:
  script:
    - "if [ -d templates ];then"
    - "erb${RUBYSUFFIX} -x -T '-' templates/*erb | ruby${RUBYSUFFIX} -c"
    - "fi"
  stage: test

rake-test:
  script:
    - "rake${RUBYSUFFIX} spec SPEC_OPTS='--format documentation'"
  stage: test

deploy:
  script:
    - "sudo /usr/local/bin/r10k${RUBYSUFFIX} deploy module ${MODULENAME} -v"
  stage: deploy
  only:
    - master

